<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <packaging>jar</packaging>

    <parent>
        <groupId>cc.uncarbon.framework</groupId>
        <artifactId>helium-starters-parent</artifactId>
        <version>${revision}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>helium-starter-ratelimiter-redis</artifactId>
    <name>${project.artifactId}</name>
    <description>
        Helium 基于 Redis 的限流器启动包
    </description>

    <dependencies>
        <!-- 引用基础启动包 -->
        <dependency>
            <groupId>cc.uncarbon.framework</groupId>
            <artifactId>helium-starter-base</artifactId>
        </dependency>

        <!-- 引用 Web 核心包 -->
        <dependency>
            <groupId>cc.uncarbon.framework</groupId>
            <artifactId>helium-core-web</artifactId>
        </dependency>

        <!-- 引用 Redis 启动包 -->
        <dependency>
            <groupId>cc.uncarbon.framework</groupId>
            <artifactId>helium-starter-redis</artifactId>
        </dependency>

        <!-- 引用 AOP 框架 -->
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-aop</artifactId>
        </dependency>

        <dependency>
            <groupId>org.aspectj</groupId>
            <artifactId>aspectjweaver</artifactId>
        </dependency>
    </dependencies>
</project>
