<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <packaging>jar</packaging>

    <parent>
        <groupId>cc.uncarbon.framework</groupId>
        <artifactId>helio-starters-parent</artifactId>
        <version>${revision}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>helio-starter-tenant</artifactId>
    <name>${project.artifactId}</name>
    <description>
        Helio 多租户启动包
    </description>

    <dependencies>
        <!-- 引用基础启动包 -->
        <dependency>
            <groupId>cc.uncarbon.framework</groupId>
            <artifactId>helio-starter-base</artifactId>
        </dependency>

        <!-- 引用配套核心包 -->
        <dependency>
            <groupId>cc.uncarbon.framework</groupId>
            <artifactId>helio-core-tenant</artifactId>
        </dependency>

        <!-- 引用集成 mybatis-plus 启动包 -->
        <!-- 用于行级租户 -->
        <dependency>
            <groupId>cc.uncarbon.framework</groupId>
            <artifactId>helio-starter-db-mybatis-plus</artifactId>
        </dependency>

        <!-- 引用集成 dynamic-datasource 启动包 -->
        <!-- 用于数据源级租户 -->
        <dependency>
            <groupId>cc.uncarbon.framework</groupId>
            <artifactId>helio-starter-db-dynamic-datasource</artifactId>
        </dependency>
    </dependencies>
</project>
