<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <packaging>jar</packaging>

    <parent>
        <groupId>cc.uncarbon.framework</groupId>
        <artifactId>helio-starters-parent</artifactId>
        <version>${revision}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>helio-starter-jackson3</artifactId>
    <name>${project.artifactId}</name>
    <description>
        Helio 集成 Jackson 3.x 启动包
    </description>

    <dependencies>
        <!-- 引用基础启动包 -->
        <dependency>
            <groupId>cc.uncarbon.framework</groupId>
            <artifactId>helio-starter-base</artifactId>
        </dependency>

        <!-- 暂无配套核心包 -->

        <!-- Spring Boot JSON 启动包 -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-json</artifactId>
        </dependency>
    </dependencies>
</project>
