<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <packaging>pom</packaging>

    <groupId>cc.uncarbon.framework</groupId>
    <artifactId>helio-starter-bom</artifactId>
    <version>${revision}</version>
    <name>${project.artifactId}</name>
    <description>
        统一管理 Helio 脚手架内部依赖的版本号
    </description>

    <properties>
        <revision>4.0.0-SNAPSHOT</revision>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>cc.uncarbon.framework</groupId>
                <artifactId>helio-core-base</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>cc.uncarbon.framework</groupId>
                <artifactId>helio-starter-base</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>cc.uncarbon.framework</groupId>
                <artifactId>helio-starter-jackson</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>cc.uncarbon.framework</groupId>
                <artifactId>helio-core-mybatis</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>cc.uncarbon.framework</groupId>
                <artifactId>helio-starter-mybatis</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>cc.uncarbon.framework</groupId>
                <artifactId>helio-core-redis</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>cc.uncarbon.framework</groupId>
                <artifactId>helio-starter-redis</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>cc.uncarbon.framework</groupId>
                <artifactId>helio-core-satoken</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>cc.uncarbon.framework</groupId>
                <artifactId>helio-starter-satoken</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>cc.uncarbon.framework</groupId>
                <artifactId>helio-core-tenant</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>cc.uncarbon.framework</groupId>
                <artifactId>helio-starter-tenant</artifactId>
                <version>${revision}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>
